url=jdbc:postgresql://db.ffyqbadrvtzjzvqilarj.supabase.co:5432/postgres?sslmode=require
username=postgres
password=
changeLogFile=./db/changelog.yaml
defaultSchemaName=public
logLevel=info
classpath=db