spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
logging.level.root=WARN
logging.level.com.brewbuddy=INFO
logging.level.com.brewbuddy.security=INFO
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
